version: '3.8'
services:
  web:
    build: .docker/api
    container_name: php-app
    volumes:
      - ./backend:/var/www/html
    ports:
      - "80:80"
    # depends_on:
    #   - db
    # environment:
    #   DB_HOST: db
    #   DB_PORT: 3306
    #   DB_DATABASE_FILE: /run/secrets/mysql_database
    #   DB_USERNAME_FILE: /run/secrets/mysql_user
    #   DB_PASSWORD_FILE: /run/secrets/mysql_password
    # secrets:
    #   - mysql_database
    #   - mysql_user
    #   - mysql_password
  db:
    image: mysql:8.0
    container_name: mysql-app
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
      MYSQL_DATABASE_FILE: /run/secrets/mysql_database
      MYSQL_USER_FILE: /run/secrets/mysql_user
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_password
    secrets:
      - mysql_root_password
      - mysql_database
      - mysql_user
      - mysql_password
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
  test-db:
    image: mysql:8.0
    container_name: mysql-test-app
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
      MYSQL_DATABASE_FILE: /run/secrets/mysql_test_database
      MYSQL_USER_FILE: /run/secrets/mysql_user
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_password
    secrets:
      - mysql_root_password
      - mysql_test_database
      - mysql_user
      - mysql_password
    ports:
      - "3307:3306"

secrets:
  mysql_root_password:
    file: ./secrets/mysql_root_password
  mysql_database:
    file: ./secrets/mysql_database
  mysql_test_database:
    file: ./secrets/mysql_test_database
  mysql_user:
    file: ./secrets/mysql_user
  mysql_password:
    file: ./secrets/mysql_password

volumes:
  dbdata:

