name: Backend CI/CD

on:
  push:
    branches:
      - feature**
      - fix**
  pull_request:
    branches:
      - dev
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Install dependencies
        working-directory: ./backend
        run: composer install

      - name: Copy .env
        working-directory: ./backend
        run: cp .env.example .env

      - name: Generate APP_KEY
        working-directory: ./backend
        run: php artisan key:generate

      - name: Run migrations
        working-directory: ./backend
        run: php artisan migrate --force

      - name: Run tests
        working-directory: ./backend
        run: |
          php artisan test

  create-pull-request:
    if: github.event_name == 'push'
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check and Create Pull Request
        env:
          GH_TOKEN: ${{ secrets.GITHUB_ACTION_TOKEN }}
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
        run: |
          CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
          if [ "$CURRENT_BRANCH" != "dev" ]; then
            gh pr create \
              --base dev \
              --head $CURRENT_BRANCH \
              --title "$COMMIT_MESSAGE" \
              --body "This PR is automatically created by GitHub Actions"
          else
            echo "No changes to create a PR for."
          fi
